spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 343512024748-hkfo8ibfgol8k5ivrvfu7i9nr056k8j4.apps.googleusercontent.com
            client-secret: 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
#          facebook:
#            client-id: 424572927314494
#            client-secret: e5e0e882674cefd88b15d2c3fb838fa4
#          github:
#            client-id:
#            client-secret:
