server:
  port: 8001
spring:
  security:
    oauth2:
      client:
        registration:
          google:
            client-id:
            client-secret:
#        provider:
#          google:
#            redirect-uri: http://localhost:8001/login/oauth2/code/googleflowName=GeneralOAuthFlow
#          okta:
#            client-id:
#            client-secret:
#            scope: openid, profile
#        provider:
#          okta:
#            issuer-uri: https://dev-10757845.okta.com/oauth2/default
#          facebook:
#            client-id:
#            client-secret:
#          github:
#            client-id:
#            client-secret:
logging:
  level:
    web: DEBUG
    root: INFO
